name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: "30 9 * * *"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git remote add upstream "git://git.proxmox.com/git/$(basename "$(git remote get-url origin)")"
          git fetch upstream
          for remote in $(git branch -r | grep -v /HEAD)
          do
            git checkout --track $remote
          done
          for branch in $(git branch | grep -v /HEAD)
          do
            git switch $branch
            git pull upstream $branch
          done
          git push --all --tags origin
